### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [AKWolff037/rust-demo#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by AKWolff037** [comment]
Since this is just a learning project, not really.  I should be able to replace with Serde

**Comment by AKWolff037** [comment]
rustc-serialize has been replaced with serde.
